Rails.application.routes.draw do
  root to: 'altair#home'
  get '/signup',    to: 'users#new'
  get '/signin',    to: 'sessions#new'
  get '/signout',   to: 'sessions#destroy'
  get '/im',        to: 'users#show'
  post '/upd',        to: 'users#update'
  post '/signin',   to: 'sessions#create'
  post '/signup',   to: 'users#create'
  post '/block',    to: 'block#create'
  post '/db',       to: 'uses#update'
  post 'del',     to: 'admin#destroy'
  get '/home',      to: 'altair#home'
  get '/about',     to: 'altair#about'
  get '/help',      to: 'altair#help'
  get '/contact',   to: 'altair#contact'
  get '/theory',    to: 'altair#theory'
  get '/admin',     to: 'admin#show'
  get '/block',     to: 'block#show'
  get '/db',        to: 'uses#db_con'
  get '/sh',        to: 'admin#persons'
  post '/edit',        to: 'admin#edit'


end
